fullnameOverride: "fxtask"

application:
  probes:
    readinessProbe:
      httpGet:
        path: /index.html
        port: http
      initialDelaySeconds: 5
      periodSeconds: 15
    livenessProbe:
      httpGet:
        path: /index.html
        port: http
      initialDelaySeconds: 5
      periodSeconds: 15
      timeoutSeconds: 5
  resources:
    limits:
      cpu: "0.2"
      memory: 400Mi
    requests:
      cpu: "0.1"
      memory: 200Mi

service:
  type: NodePort
  name: "proxy"
  nodePort: 32002

ingress:
  enabled: true
  className: "system-ingress"
  hosts:
    - host: fxtask.cluster.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
