apiVersion: v1
kind: Service
metadata:
  name: {{ include "fxtask.fullname" . }}-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      {{- if .Values.service.name }}
      name: {{ .Values.service.name }}
      {{- end }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "fxtask.selectorLabels" . | nindent 4 }}
